# name: PR Workflow

# on:
#   push:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Say Hello
#         run: echo "Hello from workflow"

#   say-bye:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Say Bye
#         run: echo "Hello Again"

name: Uses action

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: List files
        run: ls
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy successfully"